FROM golang:1.24-alpine AS builder
WORKDIR /build
COPY whitelist-plugin/ .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -a -installsuffix cgo \
    -ldflags "-w -s -extldflags '-static'" \
    -tags netgo \
    -o /whitelist-server ./cmd/server

FROM alpine:latest
COPY --from=builder /whitelist-server /whitelist-server
EXPOSE 8081
ENTRYPOINT ["/whitelist-server"]
