# Web of Trust Crawler Configuration

# Nostr relay to connect to for fetching follow lists
relay_url: "wss://relay.damus.io"

# Dgraph server address
dgraph_addr: "localhost:9080"

# Pubkey to crawl (hex or npub format)
# Replace with actual pubkey
pubkey: "npub1mygerccwqpzyh9pvp6pv44rskv40zutkfs38t0hqhkvnwlhagp6s3psn5p"

# Timeout for relay operations
timeout: "30s"
