#!/usr/bin/env bash
# generate_fixture.sh — regenerate tests/fixture/data.mdb from the pinned strfry image.
#
# PINNED DIGEST CONTRACT:
#   This digest MUST stay in lockstep with:
#     - Dockerfile.strfry (the production strfry image)
#     - spam/config/lmdb2graphql.yaml.example (pinned_strfry_version)
#     - spam/src/config.rs (pinned_strfry_version field)
#   Diverging any of these three breaks the correctness guarantee that
#   lmdb2graphql's comparators match the live strfry instance.
#
# DETERMINISM:
#   Per reference/PROVENANCE.md §A5: two independent `strfry import` runs on the
#   same seed_events.jsonl produce byte-identical data.mdb.
#   levId is assigned monotonically in import order — seed events are fed via
#   stdin in file order to preserve this invariant. (RESEARCH.md Pitfall 4)
#
# USAGE:
#   bash tests/generate_fixture.sh          # from spam/ directory
#
# REQUIREMENTS:
#   - Docker available (docker CLI in PATH)
#   - tests/fixture/seed_events.jsonl exists (committed in the repo)
#
# This script is called by CI (.github/workflows/lmdb2graphql.yml) after
# pulling the pinned strfry image, and can also be run locally.

set -euo pipefail

STRFRY_IMAGE="dockurr/strfry@sha256:545555da5dd2c2b502f2c0d159f4dc4996d0e488e3bf25905ce881722d63d2c5"

# Resolve fixture directory relative to this script (works regardless of cwd).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FIXTURE_DIR="$SCRIPT_DIR/fixture"
SEED_FILE="$FIXTURE_DIR/seed_events.jsonl"

if [ ! -f "$SEED_FILE" ]; then
  echo "ERROR: seed file not found: $SEED_FILE" >&2
  exit 1
fi

echo "generate_fixture.sh: using pinned strfry image $STRFRY_IMAGE"
echo "generate_fixture.sh: seed file: $SEED_FILE"
echo "generate_fixture.sh: fixture dir: $FIXTURE_DIR"

# Create a temp working directory for the strfry run.
# We regenerate to a temp location first; copy into tests/fixture/ only after success.
# This prevents partial overwrites if something fails mid-run (RESEARCH.md Anti-Pattern 3).
TMPDIR_WORK="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_WORK"' EXIT

TMPDB="$TMPDIR_WORK/strfry-db"
mkdir -p "$TMPDB"

# Write a minimal strfry config pointing at the temp DB.
# mapsize matches the contract in PROVENANCE.md and lmdb2graphql.yaml.example (10 TiB).
STRFRY_CONF="$TMPDIR_WORK/strfry.conf"
cat > "$STRFRY_CONF" <<'STRFRY_CONF_EOF'
db = "/work/strfry-db/"
dbParams {
  maxreaders = 256
  mapsize = 10995116277760
  noReadAhead = false
}
STRFRY_CONF_EOF

echo "generate_fixture.sh: importing seed events..."

# Import seed events in deterministic file order (no sort — preserve JSONL order).
# levId is monotonic per insertion order; file order is the golden-vector contract.
# Feed events via stdin so the container never needs to mount the host seed file.
docker run --rm -i \
  --ulimit nofile=1000000:1000000 \
  -v "$TMPDIR_WORK":/work \
  --entrypoint /app/strfry \
  "$STRFRY_IMAGE" \
  --config=/work/strfry.conf import \
  < "$SEED_FILE"

echo "generate_fixture.sh: import complete."

# Verify the generated LMDB files exist before touching the committed fixture.
if [ ! -f "$TMPDB/data.mdb" ]; then
  echo "ERROR: strfry import did not produce $TMPDB/data.mdb" >&2
  exit 1
fi

# Copy into tests/fixture/ — this replaces the committed files.
# lock.mdb is generated by LMDB; copy it alongside data.mdb.
cp "$TMPDB/data.mdb" "$FIXTURE_DIR/data.mdb"
if [ -f "$TMPDB/lock.mdb" ]; then
  cp "$TMPDB/lock.mdb" "$FIXTURE_DIR/lock.mdb"
fi

# Print sha256 for operator verification against PROVENANCE.md.
echo "generate_fixture.sh: fixture regenerated successfully."
echo ""
if command -v sha256sum >/dev/null 2>&1; then
  echo "data.mdb sha256: $(sha256sum "$FIXTURE_DIR/data.mdb" | awk '{print $1}')"
elif command -v shasum >/dev/null 2>&1; then
  echo "data.mdb sha256: $(shasum -a 256 "$FIXTURE_DIR/data.mdb" | awk '{print $1}')"
fi
echo ""
echo "Committed reference sha256 (PROVENANCE.md): 8b871be80f8acaa507741b8640a25a411ee7763b0c4e61bb9527314d1fcb3cd6"
echo "Run 'cargo test' to verify the fixture passes the comparator self-check."
