use heed::{EnvFlags, EnvOpenOptions};
use std::path::Path;

/// Open the strfry LMDB environment read-only.
///
/// `map_size` MUST be >= strfry's configured mapsize (10995116277760 = 10 TiB per
/// ../config/strfry/strfry.conf line: mapsize = 10995116277760).
///
/// Safety: EnvOpenOptions::open is unsafe because incorrect map_size or path can corrupt
/// the environment or cause undefined behavior. Callers must ensure path points to a valid
/// strfry LMDB directory and map_size >= strfry's configured mapsize.
///
/// T-01-01 mitigation: EnvFlags::READ_ONLY prevents any write transaction at the LMDB
/// level. No write-transaction helper is exposed by this module.
pub fn open_read_only_env(db_path: &Path, map_size: usize) -> heed::Result<heed::Env> {
    unsafe {
        EnvOpenOptions::new()
            .max_dbs(20) // >= number of named sub-DBs in strfry
            .map_size(map_size) // must be >= strfry.conf mapsize (10 TiB)
            .flags(EnvFlags::READ_ONLY)
            .open(db_path)
    }
}

/// Open a fixture LMDB environment for CI tests only.
///
/// Uses NO_LOCK in addition to READ_ONLY — safe when strfry is NOT running against the
/// same environment (CI-only fixture with no concurrent writer). NEVER use in production.
///
/// The map_size is fixed at strfry's configured mapsize (10 TiB) since the fixture was
/// generated by a strfry instance with that mapsize.
pub fn open_fixture_env(fixture_path: &Path) -> heed::Result<heed::Env> {
    unsafe {
        EnvOpenOptions::new()
            .max_dbs(20)
            .map_size(10_995_116_277_760) // strfry.conf mapsize — required even for fixtures
            .flags(EnvFlags::READ_ONLY | EnvFlags::NO_LOCK) // NO_LOCK: CI fixture only
            .open(fixture_path)
    }
}
